import "./globals.css"
import {Poppins} from 'next/font/google'
import { AuthProvider } from "@/context/auth_context";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ["100","200", "300", "400", "500", "600", "700", "800", "900"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} bg-white dark:bg-[#17153B]`}
      >
        <AuthProvider>
            {children}
        </AuthProvider>
      </body>
    </html>
  );
}
